# Generated by Django 3.0.5 on 2020-04-21 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='source_command',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title_image',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
