# Generated by Django 3.0.5 on 2020-04-21 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200421_1014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='source_command',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
