# Generated by Django 3.0.5 on 2020-04-21 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200421_1016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title_image',
            field=models.ImageField(null=True, upload_to='.static/pic'),
        ),
    ]
