# Generated by Django 3.0.5 on 2020-04-21 06:46

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20200421_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title_image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=blog.models.path_and_rename),
        ),
    ]
